version: '1'
services:
  web:
    container_name: my-web
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    links:
      - api

  api:
    container_name: my-api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"


